name = "vellume-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "vellume-db"
database_id = "d6748e38-776c-4836-8e45-c43a617d923c"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "vellume-images"

[[kv_namespaces]]
binding = "KV"
id = "787a945fad9f4f88bcc6a448207093df"

[ai]
binding = "AI"
